/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reklamtabela;

import java.awt.CardLayout;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huseynvaliyev
 */
public class AdminGui extends javax.swing.JFrame {

    /**
     * Creates new form AdminGui
     */
    CardLayout cardlayout;
    DefaultTableModel model;
    public AdminGui() {
        initComponents();
      cardlayout = (CardLayout)(pnlCards.getLayout()); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jButtonBitmis = new javax.swing.JButton();
        jButtonKazanc = new javax.swing.JButton();
        jButtonDevam = new javax.swing.JButton();
        pnlCards = new javax.swing.JPanel();
        jPanelDevam = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelBitmis = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanelKazanc = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelKazanc = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jSearchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jLabelName.setBackground(new java.awt.Color(44, 62, 80));
        jLabelName.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(236, 241, 240));
        jLabelName.setText("İsim Soyisim");

        jButtonBitmis.setBackground(new java.awt.Color(44, 62, 80));
        jButtonBitmis.setForeground(new java.awt.Color(236, 241, 240));
        jButtonBitmis.setBorder(null);
        jButtonBitmis.setLabel("Bitmiş Reklamlar");
        jButtonBitmis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBitmisActionPerformed(evt);
            }
        });

        jButtonKazanc.setBackground(new java.awt.Color(44, 62, 80));
        jButtonKazanc.setForeground(new java.awt.Color(236, 241, 240));
        jButtonKazanc.setBorder(null);
        jButtonKazanc.setLabel("Kazanç");
        jButtonKazanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKazancActionPerformed(evt);
            }
        });

        jButtonDevam.setBackground(new java.awt.Color(44, 62, 80));
        jButtonDevam.setForeground(new java.awt.Color(236, 241, 240));
        jButtonDevam.setText("Devameden Reklamlar");
        jButtonDevam.setBorder(null);
        jButtonDevam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabelName)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBitmis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonKazanc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDevam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabelName)
                .addGap(97, 97, 97)
                .addComponent(jButtonDevam, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBitmis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonKazanc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        pnlCards.setLayout(new java.awt.CardLayout());

        jPanelDevam.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "İsim", "Soyisim", "Reklamİsmi", "Konum", "BaşlamaZamanı", "kalanzamanı", "Bütçe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelDevamLayout = new javax.swing.GroupLayout(jPanelDevam);
        jPanelDevam.setLayout(jPanelDevamLayout);
        jPanelDevamLayout.setHorizontalGroup(
            jPanelDevamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
        );
        jPanelDevamLayout.setVerticalGroup(
            jPanelDevamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        pnlCards.add(jPanelDevam, "jPanelDevam");

        jPanelBitmis.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "İsim", "Soyisim", "Reklamİsmi", "Konum", "BaşlamaZamanı", "BitişZamanı", "Bütçe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanelBitmisLayout = new javax.swing.GroupLayout(jPanelBitmis);
        jPanelBitmis.setLayout(jPanelBitmisLayout);
        jPanelBitmisLayout.setHorizontalGroup(
            jPanelBitmisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
        );
        jPanelBitmisLayout.setVerticalGroup(
            jPanelBitmisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        pnlCards.add(jPanelBitmis, "jPanelBitmis");

        jPanelKazanc.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("BaşlangıçZamanı:");

        jLabel3.setText("BitişZamanı:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setText("Kazanç:");

        jLabelKazanc.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelKazanc.setText("0");

        jSearchButton.setText("Ara");
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelKazancLayout = new javax.swing.GroupLayout(jPanelKazanc);
        jPanelKazanc.setLayout(jPanelKazancLayout);
        jPanelKazancLayout.setHorizontalGroup(
            jPanelKazancLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKazancLayout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGroup(jPanelKazancLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelKazancLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelKazanc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172))
                    .addGroup(jPanelKazancLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelKazancLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelKazancLayout.createSequentialGroup()
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(128, 128, 128))))
        );
        jPanelKazancLayout.setVerticalGroup(
            jPanelKazancLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKazancLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanelKazancLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelKazancLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanelKazancLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelKazanc))
                .addContainerGap(268, Short.MAX_VALUE))
        );

        pnlCards.add(jPanelKazanc, "jPanelKazanc");

        jSplitPane1.setRightComponent(pnlCards);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getjLabelName() {
        return jLabelName;
    }


    private void jButtonBitmisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBitmisActionPerformed
   cardlayout.show(pnlCards, "jPanelBitmis");
        ArrayList <Rapor> mylist=new ArrayList<Rapor>();
        model=(DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        try {
            mylist=DB_conection.AdminB();
            if(!mylist.isEmpty()){
                Object rowData[]=new Object[7];
                for(int i=0; i<mylist.size(); i++){
                    rowData[0]=mylist.get(i).getAd();
                    rowData[1]=mylist.get(i).getSoyad();
                    rowData[2]=mylist.get(i).getReklaminismi();
                    rowData[3]=mylist.get(i).getKonum();
                    rowData[4]=mylist.get(i).getbaslamazamani();
                    rowData[5]=mylist.get(i).getbaslamazamani();
                    rowData[6]=mylist.get(i).getButce();
                    model.addRow(rowData);
               }
            }
            else
                JOptionPane.showMessageDialog(rootPane, "su an bitmis  reklam yoktur");
        } catch (SQLException ex) {
            Logger.getLogger(AdminGui.class.getName()).log(Level.SEVERE, null, ex);
        }
              
    }//GEN-LAST:event_jButtonBitmisActionPerformed

    private void jButtonKazancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKazancActionPerformed
        cardlayout.show(pnlCards, "jPanelKazanc");
    }//GEN-LAST:event_jButtonKazancActionPerformed

    private void jButtonDevamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevamActionPerformed
        cardlayout.show(pnlCards, "jPanelDevam");
        ArrayList <Rapor> mylist=new ArrayList<Rapor>();
        model=(DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        try {
            mylist=DB_conection.AdminD();
            if(!mylist.isEmpty()){
                model=(DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                Object rowData[]=new Object[7];
                for(int i=0; i<mylist.size(); i++){
                    rowData[0]=mylist.get(i).getAd();
                    rowData[1]=mylist.get(i).getSoyad();
                    rowData[2]=mylist.get(i).getReklaminismi();
                    rowData[3]=mylist.get(i).getKonum();
                    rowData[4]=mylist.get(i).getbaslamazamani();
                    rowData[5]=mylist.get(i).getKalansure()+" saat";
                    rowData[6]=mylist.get(i).getButce();
                    
                    model.addRow(rowData);
               }
            }
            else
                JOptionPane.showMessageDialog(rootPane, "devam eden reklam yok");
        } catch (SQLException ex) {
            Logger.getLogger(AdminGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_jButtonDevamActionPerformed

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
       Date date =jDateChooser1.getDate();
       String baslangic =DateFormat.getDateInstance().format(date);
       Date date1 =jDateChooser2.getDate();
       String bitis=DateFormat.getDateInstance().format(date1);
       System.out.println(date+" "+date1);
        try {
            int i= DB_conection.adminkazanc(baslangic, bitis);
            
            if (i!=0)
                jLabelKazanc.setText(String.valueOf(i));
            else
                JOptionPane.showMessageDialog(rootPane, "bu zaman aralik kazanc bulunmamakda");
            
        } catch (SQLException ex) {
            Logger.getLogger(AdminGui.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jSearchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminGui().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBitmis;
    private javax.swing.JButton jButtonDevam;
    private javax.swing.JButton jButtonKazanc;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelKazanc;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBitmis;
    private javax.swing.JPanel jPanelDevam;
    private javax.swing.JPanel jPanelKazanc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel pnlCards;
    // End of variables declaration//GEN-END:variables
}
