/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reklamtabela;

//import com.sun.xml.internal.ws.api.streaming.XMLStreamWriterFactory;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.ComponentListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huseynvaliyev
 */
public class KullaniciGui extends javax.swing.JFrame {

    /**
     * Creates new form KullaniciGui
     */
    DefaultComboBoxModel cm;
    DefaultTableModel model;
    CardLayout cardlayout;
    public KullaniciGui() {
        initComponents();
        
        cardlayout = (CardLayout)(pnlCards.getLayout()); 
        jComboBox2.setVisible(false);
        jLabel3.setVisible(false);
        jComboBox3.setVisible(false);
        jLabel4.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jLabelName2 = new javax.swing.JLabel();
        jButtonBitmis2 = new javax.swing.JButton();
        jButtonReklam = new javax.swing.JButton();
        jButtonDevam2 = new javax.swing.JButton();
        jButtonButce = new javax.swing.JButton();
        jLabelName3 = new javax.swing.JLabel();
        pnlCards = new javax.swing.JPanel();
        jPanelDevam = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelBitmis = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanelReklam = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jPanelButce = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabelKazanc1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane3.setPreferredSize(new java.awt.Dimension(1001, 538));

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));

        jLabelName2.setBackground(new java.awt.Color(44, 62, 80));
        jLabelName2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelName2.setForeground(new java.awt.Color(236, 241, 240));
        jLabelName2.setText(" İsim ");

        jButtonBitmis2.setBackground(new java.awt.Color(44, 62, 80));
        jButtonBitmis2.setForeground(new java.awt.Color(236, 241, 240));
        jButtonBitmis2.setLabel("Bitmiş Reklamlar");
        jButtonBitmis2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBitmis2ActionPerformed(evt);
            }
        });

        jButtonReklam.setBackground(new java.awt.Color(44, 62, 80));
        jButtonReklam.setForeground(new java.awt.Color(236, 241, 240));
        jButtonReklam.setText("Reklam Ver");
        jButtonReklam.setBorder(null);
        jButtonReklam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReklamActionPerformed(evt);
            }
        });

        jButtonDevam2.setBackground(new java.awt.Color(44, 62, 80));
        jButtonDevam2.setForeground(new java.awt.Color(236, 241, 240));
        jButtonDevam2.setText("Devameden Reklamlar");
        jButtonDevam2.setBorder(null);
        jButtonDevam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevam2ActionPerformed(evt);
            }
        });

        jButtonButce.setBackground(new java.awt.Color(44, 62, 80));
        jButtonButce.setForeground(new java.awt.Color(236, 241, 240));
        jButtonButce.setText("Bütçe");
        jButtonButce.setBorder(null);
        jButtonButce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonButceActionPerformed(evt);
            }
        });

        jLabelName3.setBackground(new java.awt.Color(44, 62, 80));
        jLabelName3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelName3.setForeground(new java.awt.Color(236, 241, 240));
        jLabelName3.setText("soyisim");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBitmis2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonReklam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDevam2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonButce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelName3, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jLabelName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabelName2)
                .addGap(32, 32, 32)
                .addComponent(jLabelName3)
                .addGap(41, 41, 41)
                .addComponent(jButtonDevam2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBitmis2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonReklam, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonButce, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jSplitPane3.setLeftComponent(jPanel3);

        pnlCards.setLayout(new java.awt.CardLayout());

        jPanelDevam.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "İsim", "Soyisim", "Reklamİsmi", "Konum", "BaşlamaZamanı", "kalanzaman", "Bütçe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelDevamLayout = new javax.swing.GroupLayout(jPanelDevam);
        jPanelDevam.setLayout(jPanelDevamLayout);
        jPanelDevamLayout.setHorizontalGroup(
            jPanelDevamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        jPanelDevamLayout.setVerticalGroup(
            jPanelDevamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );

        pnlCards.add(jPanelDevam, "jPanelDevam");

        jPanelBitmis.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "İsim", "Soyisim", "Reklamİsmi", "Konum", "BaşlamaZamanı", "BitişZamanı", "Bütçe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanelBitmisLayout = new javax.swing.GroupLayout(jPanelBitmis);
        jPanelBitmis.setLayout(jPanelBitmisLayout);
        jPanelBitmisLayout.setHorizontalGroup(
            jPanelBitmisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        jPanelBitmisLayout.setVerticalGroup(
            jPanelBitmisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );

        pnlCards.add(jPanelBitmis, "jPanelBitmis");

        jPanelReklam.setBackground(new java.awt.Color(255, 255, 255));
        jPanelReklam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelReklam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Reklam İsmi:");
        jPanelReklam.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, 22));

        jTextField7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanelReklam.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 60, 121, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("İl:");
        jPanelReklam.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 92, 91, 26));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("İlçe:");
        jPanelReklam.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 139, 91, 27));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tabela:");
        jPanelReklam.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 189, -1, 27));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Kalabalık:");
        jPanelReklam.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 241, -1, -1));

        jTextField8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanelReklam.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 237, 121, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Süre(saat):");
        jPanelReklam.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 284, -1, -1));

        jTextField9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanelReklam.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 280, 121, -1));

        jButton2.setText("Ekle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanelReklam.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 323, 97, 39));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanelReklam.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 92, 121, 32));

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanelReklam.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 187, 121, 32));

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanelReklam.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 137, 121, 32));

        pnlCards.add(jPanelReklam, "jPanelReklam");

        jPanelButce.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("Bütçe:");

        jLabelKazanc1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelKazanc1.setText("0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Kartın Numarası:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Kartın Üzerindeki İsim:");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("CVC:");

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Fiyat:");

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Son Kullanma Tarihi:");

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jButton1.setText("Artır");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButceLayout = new javax.swing.GroupLayout(jPanelButce);
        jPanelButce.setLayout(jPanelButceLayout);
        jPanelButceLayout.setHorizontalGroup(
            jPanelButceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelButceLayout.createSequentialGroup()
                .addGroup(jPanelButceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelButceLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelKazanc1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelButceLayout.createSequentialGroup()
                        .addGroup(jPanelButceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelButceLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanelButceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelButceLayout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelButceLayout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanelButceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanelButceLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 345, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelButceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanelButceLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelButceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelButceLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(561, Short.MAX_VALUE)))
        );
        jPanelButceLayout.setVerticalGroup(
            jPanelButceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButceLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelButceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelButceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelButceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelButceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(jPanelButceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelKazanc1))
                .addGap(22, 22, 22))
            .addGroup(jPanelButceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelButceLayout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(448, Short.MAX_VALUE)))
        );

        pnlCards.add(jPanelButce, "jPanelButce");

        jSplitPane3.setRightComponent(pnlCards);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getjLabelName2() {
        return jLabelName2;
    }

    public JLabel getjLabelName3() {
        return jLabelName3;
    }
    
    
    private void jButtonBitmis2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBitmis2ActionPerformed
        cardlayout.show(pnlCards, "jPanelBitmis");
         ArrayList <Rapor> mylist=new ArrayList<Rapor>();
        try {
            mylist=DB_conection.KullaniciB(jLabelName2.getText(), jLabelName3.getText());
            model=(DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);
            if(!mylist.isEmpty()){

                Object rowData[]=new Object[7];
                for(int i=0; i<mylist.size(); i++){
                    rowData[0]=mylist.get(i).getAd();
                    rowData[1]=mylist.get(i).getSoyad();
                    rowData[2]=mylist.get(i).getReklaminismi();
                    rowData[3]=mylist.get(i).getKonum();
                    rowData[4]=mylist.get(i).getbaslamazamani();
                    rowData[5]=mylist.get(i).getbitmezamani();
                    rowData[6]=mylist.get(i).getButce();
                    model.addRow(rowData);
               }
            }
            else
                JOptionPane.showMessageDialog(rootPane, "bitmis  reklam yok");
        } catch (SQLException ex) {
            Logger.getLogger(AdminGui.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_jButtonBitmis2ActionPerformed

    private void jButtonReklamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReklamActionPerformed
        try {
           String il[]=new String[81];
           il= DB_conection.ilbulma();
           cm= new DefaultComboBoxModel(il);
           jComboBox1.setModel(cm); 
           
        } catch (SQLException ex) {
            Logger.getLogger(KullaniciGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        cardlayout.show(pnlCards, "jPanelReklam");
    }//GEN-LAST:event_jButtonReklamActionPerformed

    private void jButtonDevam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevam2ActionPerformed
        cardlayout.show(pnlCards, "jPanelDevam");
        ArrayList <Rapor> mylist=new ArrayList<Rapor>();
        try {
            mylist=DB_conection.KullaniciD(jLabelName2.getText(), jLabelName3.getText());
            model=(DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            if(!mylist.isEmpty()){
                
                Object rowData[]=new Object[7];
                for(int i=0; i<mylist.size(); i++){
                    rowData[0]=mylist.get(i).getAd();
                    rowData[1]=mylist.get(i).getSoyad();
                    rowData[2]=mylist.get(i).getReklaminismi();
                    rowData[3]=mylist.get(i).getKonum();
                    rowData[4]=mylist.get(i).getbaslamazamani();
                    rowData[5]=mylist.get(i).getKalansure();
                    rowData[6]=mylist.get(i).getButce();
                    model.addRow(rowData);
               }
            }
            else
                JOptionPane.showMessageDialog(rootPane, "davam eden reklam yok");
        } catch (SQLException ex) {
            Logger.getLogger(AdminGui.class.getName()).log(Level.SEVERE, null, ex);
        }        
        
    }//GEN-LAST:event_jButtonDevam2ActionPerformed

    private void jButtonButceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonButceActionPerformed
        cardlayout.show(pnlCards, "jPanelButce");

        try {
            int i=DB_conection.butcesorgulama(jLabelName2.getText(),jLabelName3.getText());
            System.out.println(i);
            jLabelKazanc1.setText(String.valueOf(i));
        } catch (SQLException ex) {
            Logger.getLogger(KullaniciGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonButceActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      String selectedValue = (String) jComboBox1.getSelectedItem();
         try {
            jComboBox2.setVisible(true);
            jLabel3.setVisible(true); 
            cm = (DefaultComboBoxModel) jComboBox2.getModel();
            cm.removeAllElements();
             
             ArrayList <String> al =new ArrayList<String>();
             al=DB_conection.ilceler(selectedValue);
             for(int i=0; i<al.size(); i++)
                 jComboBox2.addItem(al.get(i));
             
               // cm = new DefaultComboBoxModel(al);
               // jComboBox2.setModel(cm);
             
            
        } catch (SQLException ex) {
            Logger.getLogger(KullaniciGui.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
      String selectedValue = (String) jComboBox2.getSelectedItem();
         try {
            jComboBox3.setVisible(true);
            jLabel4.setVisible(true); 
            cm = (DefaultComboBoxModel) jComboBox3.getModel();
            cm.removeAllElements();
             
             ArrayList <String> al =new ArrayList<String>();
             al=DB_conection.tabelala(selectedValue);
             for(int i=0; i<al.size(); i++)
                 jComboBox3.addItem(al.get(i));
             
               // cm = new DefaultComboBoxModel(al);
               // jComboBox2.setModel(cm);
             
            
        } catch (SQLException ex) {
            Logger.getLogger(KullaniciGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String str=jComboBox1.getSelectedItem()+"/"+jComboBox2.getSelectedItem()+"/"+jComboBox3.getSelectedItem();
        try {
            int i=DB_conection.butcesorgulama(jLabelName2.getText(),jLabelName3.getText());
            int j=Integer.parseInt(jTextField9.getText())*5;
            if(i>=j){
                DB_conection.ReklamVer(jLabelName2.getText(), jLabelName3.getText(), jTextField7.getText(),str , Integer.parseInt(jTextField9.getText()),Integer.parseInt(jTextField8.getText()));
                JOptionPane.showMessageDialog(rootPane, "reklam eklendi");
            }
            else
              JOptionPane.showMessageDialog(rootPane, "butceniz yeterli deyil butce="+i);
        } catch (SQLException ex) {
            Logger.getLogger(KullaniciGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
        DB_conection.butceartir(jLabelName2.getText(), jLabelName3.getText(), Integer.parseInt(jTextField6.getText()));
        int i=DB_conection.butcesorgulama(jLabelName2.getText(), jLabelName3.getText());
        jLabelKazanc1.setText(String.valueOf(i));
        
       } catch (SQLException ex) {
            Logger.getLogger(KullaniciGui.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments   
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullaniciGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBitmis2;
    private javax.swing.JButton jButtonButce;
    private javax.swing.JButton jButtonDevam2;
    private javax.swing.JButton jButtonReklam;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelKazanc1;
    private javax.swing.JLabel jLabelName2;
    private javax.swing.JLabel jLabelName3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelBitmis;
    private javax.swing.JPanel jPanelButce;
    private javax.swing.JPanel jPanelDevam;
    private javax.swing.JPanel jPanelReklam;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel pnlCards;
    // End of variables declaration//GEN-END:variables

  
}
